// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"asong.cloud/go-algorithm/leaf/common"
	"asong.cloud/go-algorithm/leaf/config"
	"asong.cloud/go-algorithm/leaf/dao"
	"asong.cloud/go-algorithm/leaf/handler"
	"asong.cloud/go-algorithm/leaf/model"
	"asong.cloud/go-algorithm/leaf/service"
)

// Injectors from wire.go:

func InitializeHandler(conf *config.Server) *handler.LeafHandler {
	engine := common.NewRouterClient()
	db := common.NewMysqlClient(conf)
	leafDB := dao.NewLeafDB(db)
	leafDao := dao.NewLeafDAO(leafDB, db)
	leafSeq := model.NewLeafSeq()
	leafService := service.NewLeafService(leafDao, leafSeq)
	leafHandler := handler.NewLeafHandler(engine, leafService)
	return leafHandler
}
